"""
PocketPlot Universe - Story Remix (v17).

Takes an existing world and produces a new one in a different genre
while preserving the core plot + characters.

Two remix engines:
  - procedural (default): deterministic, no LLM, fast, offline.
    Re-seeds the world with a new genre but keeps the spec.
  - BYOB: routes through the user's external_api_manager BYOB LLM
    (Creator tier). The LLM gets the existing spec + new genre as a
    prompt and returns a transformed spec.

In both cases the original world is untouched and a new world row
is created. The remix_history table records the lineage.
"""
import datetime as dt
import json
import logging
import random

log = logging.getLogger("pocketplot.remix")


def _now() -> str:
    return dt.datetime.utcnow().isoformat(timespec="seconds") + "Z"


def _load_world(db, world_id: int) -> dict | None:
    conn = db()
    row = conn.execute(
        "SELECT * FROM worlds WHERE id=?", (world_id,),
    ).fetchone()
    conn.close()
    return dict(row) if row else None


def _load_episodes(db, world_id: int) -> list:
    conn = db()
    rows = conn.execute(
        "SELECT episode_number, title, body, choices_json FROM world_episodes "
        "WHERE world_id=? ORDER BY episode_number",
        (world_id,),
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]


def _remix_title(original_title: str, to_genre: str) -> str:
    """Generate a remix title that signals the new genre."""
    base = original_title.rstrip(".")
    suffix_map = {
        "cyberpunk":   "in Neon",
        "romance":     "in Bloom",
        "action":      "Reloaded",
        "drama":       "Darker",
        "thriller":    "Unsafely",
        "fantasy":     "Reimagined",
        "comedy":      "Mishaps",
        "scifi":       "v2.0",
        "horror":      "in Shadow",
        "detective":   "Reopened",
        "fairytales":  "Re-Told",
        "superhero":   "Relaunched",
        "chicklit":    "Season 2",
        "adventure":   "Recharted",
        "roleplaying": "in Another Age",
        "historical":  "Revisited",
    }
    suffix = suffix_map.get(to_genre, "Remixed")
    return f"{base} ({suffix})"


def _remix_spec(original_spec: dict, to_genre: str, to_tone: str) -> dict:
    """Translate the spec to a new genre + tone. Keeps the core identity.

    The transformation is light: character + objective stay (they ARE
    the story), but we tag the spec with the new genre + tone so the
    procedural engine and the scene composer pick the right palette.
    """
    out = dict(original_spec or {})
    out["remixed_from_genre"] = out.get("genre", "")
    out["remixed_to_genre"] = to_genre
    out["genre"] = to_genre
    out["tone"] = to_tone
    out["remix_note"] = (
        f"Preserves the original character + objective; sets new genre="
        f"{to_genre} and tone={to_tone}. Generated by story_remix."
    )
    return out


def _create_remix(db, owner_id: int, original_title: str,
                    to_genre: str, to_tone: str, spec: dict,
                    from_genre: str) -> int:
    """Create a new world row as the remix container. Returns new world id."""
    import story_world as sw
    new_title = _remix_title(original_title, to_genre)
    seed = int(dt.datetime.utcnow().timestamp()) % (2**31)
    return sw.create_world(db, owner_id, title=new_title,
                            genre=to_genre, tone=to_tone,
                            setting=spec.get("setting", "a quiet place"),
                            seed=seed, spec=spec)


def _save_remix_history(db, original_world_id: int, new_world_id: int,
                          from_genre: str, to_genre: str) -> None:
    conn = db()
    conn.execute(
        "INSERT INTO remix_history(original_world_id, new_world_id, "
        "from_genre, to_genre, created_at) VALUES (?, ?, ?, ?, ?)",
        (original_world_id, new_world_id, from_genre, to_genre, _now()),
    )
    conn.commit()
    conn.close()


# ---- PUBLIC ENTRY POINTS ----

def remix_procedural(db, world_id: int, to_genre: str, to_tone: str = None) -> dict:
    """Deterministic procedural remix. No LLM, no external calls.

    Returns {"ok": True, "new_world_id": int, "from_genre": str, "to_genre": str}
    or {"ok": False, "error": str}.
    """
    original = _load_world(db, world_id)
    if not original:
        return {"ok": False, "error": f"world {world_id} not found"}
    from_genre = original.get("genre") or "fantasy"
    if to_genre == from_genre:
        return {"ok": False, "error": "remix genre must differ from original"}

    # Decode the existing spec (if any).
    try:
        original_spec = json.loads(original.get("state_json") or "{}").get("spec") or {}
    except Exception:
        original_spec = {}

    # Pick a default tone if the user didn't specify one.
    if not to_tone:
        to_tone = _pick_complementary_tone(from_genre, to_genre)

    new_spec = _remix_spec(original_spec, to_genre, to_tone)

    try:
        new_id = _create_remix(db, original["subscriber_id"], original["title"],
                                 to_genre, to_tone, new_spec, from_genre)
    except Exception as e:
        return {"ok": False, "error": str(e)}

    _save_remix_history(db, world_id, new_id, from_genre, to_genre)
    return {"ok": True, "new_world_id": new_id,
              "from_genre": from_genre, "to_genre": to_genre,
              "to_tone": to_tone}


def remix_byob(db, world_id: int, to_genre: str, to_tone: str,
                *, subscriber_id: int) -> dict:
    """BYOB LLM remix. Requires an external_api_keys row for this subscriber.

    Falls back to procedural remix if no BYOB key is configured. The LLM
    is asked to transform the original spec into the new genre while
    preserving the core character + objective.
    """
    # Check for a BYOB key first.
    try:
        import external_api_manager as eam
        keys = eam.list_keys_for_subscriber(db, subscriber_id)
    except Exception as e:
        keys = []
    if not keys:
        log.info("no BYOB keys for sub=%s - falling back to procedural remix",
                  subscriber_id)
        return remix_procedural(db, world_id, to_genre, to_tone)

    original = _load_world(db, world_id)
    if not original:
        return {"ok": False, "error": f"world {world_id} not found"}
    from_genre = original.get("genre") or "fantasy"
    if to_genre == from_genre:
        return {"ok": False, "error": "remix genre must differ from original"}

    try:
        original_spec = json.loads(original.get("state_json") or "{}").get("spec") or {}
    except Exception:
        original_spec = {}

    prompt = _build_byob_prompt(original_spec, from_genre, to_genre, to_tone)
    try:
        # Pick the user's first BYOB key.
        llm_response = eam.call_llm(db, subscriber_id=subscriber_id,
                                       messages=[
                                           {"role": "system",
                                            "content": "You transform story "
                                                       "specs while preserving "
                                                       "characters."},
                                           {"role": "user",
                                            "content": prompt},
                                       ],
                                       max_tokens=900)
    except Exception as e:
        log.warning("BYOB remix failed, falling back: %s", e)
        return remix_procedural(db, world_id, to_genre, to_tone)

    # Best-effort parse: the LLM should return JSON, but we accept any text.
    new_spec = _parse_llm_spec(llm_response, original_spec, to_genre, to_tone)
    try:
        new_id = _create_remix(db, original["subscriber_id"], original["title"],
                                 to_genre, to_tone, new_spec, from_genre)
    except Exception as e:
        return {"ok": False, "error": str(e)}
    _save_remix_history(db, world_id, new_id, from_genre, to_genre)
    return {"ok": True, "new_world_id": new_id,
              "from_genre": from_genre, "to_genre": to_genre,
              "to_tone": to_tone, "byob": True}


def _pick_complementary_tone(from_genre: str, to_genre: str) -> str:
    """Pick a tone that contrasts with the source genre for a real remix feel."""
    contrast = {
        "fantasy":    "mysterious",
        "scifi":      "hopeful",
        "romance":    "epic",
        "thriller":   "whimsical",
        "comedy":     "dark",
        "drama":      "whimsical",
        "horror":     "hopeful",
        "cyberpunk":  "romantic",
        "adventure":  "mysterious",
        "detective":  "epic",
        "fairytales": "dark",
        "superhero":  "mysterious",
        "chicklit":   "epic",
        "roleplaying": "dark",
        "historical": "epic",
        "action":     "mysterious",
    }
    return contrast.get(to_genre, "hopeful")


def _build_byob_prompt(spec: dict, from_genre: str, to_genre: str, to_tone: str) -> str:
    """Build the LLM prompt for a remix."""
    return (
        "You are a story remixer. Preserve the character identity and core "
        "objective from the original, but transform the genre and tone.\n\n"
        f"Original genre: {from_genre}\n"
        f"New genre: {to_genre}\n"
        f"New tone: {to_tone}\n\n"
        "Original spec (preserve character_description and primary_objective "
        "verbatim, adjust setting/tone to fit the new genre):\n"
        + json.dumps(spec, indent=2)
        + "\n\nReturn a JSON object with these keys: "
        "character_description, primary_objective, setting, tone, genre.\n"
        "Output ONLY valid JSON."
    )


def _parse_llm_spec(llm_response: str, fallback_spec: dict,
                     to_genre: str, to_tone: str) -> dict:
    """Best-effort parse of the LLM's response into a spec dict."""
    text = (llm_response or "").strip()
    # Strip leading/trailing code fences.
    if text.startswith("```"):
        text = text.split("```", 2)[1] if "```" in text else text
        text = text.strip()
    try:
        parsed = json.loads(text)
        if isinstance(parsed, dict):
            return _remix_spec(parsed, to_genre, to_tone)
    except Exception:
        pass
    # Fall back to the original spec, just retagged with the new genre/tone.
    return _remix_spec(fallback_spec, to_genre, to_tone)


def list_remixes(db, world_id: int) -> list:
    """All remix-history rows where the source is `world_id`."""
    conn = db()
    rows = conn.execute(
        "SELECT h.*, w.title AS new_title FROM remix_history h "
        "JOIN worlds w ON h.new_world_id=w.id "
        "WHERE h.original_world_id=? ORDER BY h.created_at DESC",
        (world_id,),
    ).fetchall()
    conn.close()
    return [dict(r) for r in rows]
